import type { Metadata } from "next";
import {Inter, Roboto, Josefin_Sans, Playfair, Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import bgImg from '@/../public/bgrepeat.png';

const ubuntu = Ubuntu_Mono({
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
  weight: "400"
})

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
})

const josefin = Josefin_Sans({
      variable: '--font-josefin',
      subsets: ['latin'],
})

const playfair = Playfair({
  variable: '--font-playfair',
      subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${inter.variable} ${josefin.variable} ${playfair.variable} ${ubuntu.variable}`}>
       {children}
      </body>
    </html>
  );
}
